### ISSUE TITLE
Not longer supported?

### ISSUE THREAD

**Issue by Photograaf16** [JeffResc/DelTrack#4]
Sadly enough when i tried your app it told me some things were unsupported and needed to upgrade.
I tried to do this but without success!
Could you try when you have time to fix it maybe?
thanks in advance!

``
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice
npm notice New minor version of npm available! 8.8.0 -> 8.10.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>
npm notice Run `npm install -g npm@8.10.0` to update!
npm notice
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/JeffResc/delivery-tracker/tarball/master
npm ERR! 404
npm ERR! 404  'delivery-tracker@https://github.com/JeffResc/delivery-tracker/tarball/master' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
``

**Comment by JeffResc** [comment]
Hi @Photograaf15,

I'm sorry that your experiencing issues while trying to run the project. Can you walk me through your install process, how you tried to run it, and any troubleshooting you may have tried?

**Comment by Photograaf16** [comment]
Hi! 
First, I tried to spin it up with docker but after getting the same issue as listed in the first post I tried to run it from my own main pc with nodeJS and NPM installed. after I saw I got the same issue I tried to edit the package dependencies to match what node told me to require. but without luck!

The command for trying to install the needed packages: npm i (as you mentioned)

EDIT:
btw when I try to go to the dependency that gave the issue:
https://github.com/JeffResc/delivery-tracker/tarball/master

it gives a 404 error so I'm afraid it has been removed

**Comment by Photograaf16** [comment]
Update!
To fix the issue i need to change this line(line 5 in package.json):
"delivery-tracker": "https://github.com/JeffResc/delivery-tracker/tarball/master",

to:

"delivery-tracker": "https://github.com/egg-/delivery-tracker/tarball/master",

then your program works perfectly fine!
